---
title: "Database query for: [request name and ID]"
author: "Your name here"
date: "`r Sys.Date()`"
format: html
embed-resources: true
editor: source
---

<!-- To install the DaSL Quarto theme: 
      quarto install extension fhdsl/dasl-quarto 
      Then change format to `dasl-html` -->

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(here)
library(glue)
```

```{r connections}

caisis <- DBI::dbConnect(
  odbc::odbc(),
  Driver   = "SQL Server", # or use "ODBC Driver 18 for SQL Server" for mac
  Server   = "CONGO-H\\H",
  Database = "CaisisProd",
  Trusted_Connection = "yes"
  )

hidra <- DBI::dbConnect(
  odbc::odbc(),
  Driver   = "SQL Server",
  Server   = "CONGO-H\\H",
  Database = "ccod_rep_prod",
  trusted_connection = "yes"
  )

amalga <- DBI::dbConnect(
  odbc::odbc(),
  Driver   = "SQL Server",
  Server   = "CONGO-H\\H",
  Database = "uw_rep_cdrv2shim_prod",
  trusted_connection = "yes"
  )

hdc_rep_staging_prod <- DBI::dbConnect(
  odbc::odbc(),
  Driver   = "SQL Server",
  Server   = "CONGO-H\\H",
  Database = "hdc_rep_staging_prod",
  trusted_connection = "yes"
  )
```

## Define cohort

<!-- Use the inclusion and exclusion criteria in the data plan to find the 
      cohort of patients -->
      
```{sql, cohort-selection, connection=, output.var="cohort"}

```

## Construct datasets

<!-- Create data sets for the identified cohort -->

```{sql, encounters, connection=, output.var="encounters"}

```

```{r cohort-characteristics}
cohort_ids <- paste0(
  "'",
  paste0(unique(cohort$PatientMrnUwmc), collapse = "', '"),
  "'"
  )

query <- glue("
  select
    PatientMrnUwmc,
    Sex,
    GenderIdentity,
    BirthDateDurableKey,
    Status,
    DeathDate,
    Races,
    Ethnicity
  from
    pipeline.PatientDim
  where 
    PatientMrnUwmc in ({cohort_ids})
")

cohort_characteristics <- as_tibble(DBI::dbGetQuery(hidra, query)) 
```

## Write to `data/`

```{r write-csvs}
datasets <- c(
  "cohort",
  "encounters"
)

save_csv <- function(df) {
  write_csv(get(df), here("data", paste0(df, ".csv")), na = "")
  }

purrr::walk(datasets, save_csv)
```




